[build]
  command = "./build.sh"
  publish = "iclassifier_testing_clone/dist/spa"
  functions = "iclassifier_testing_clone/netlify/functions"


[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

# Serve React app for /projects and its routes
[[redirects]]
  from = "/projects"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/project/*"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/reports/*"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/bug-report"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/contact-us"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/user-manual"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/debug-projects"
  to = "/app.html"
  status = 200
